name: Django CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies with Poetry
        run: poetry install --no-root

      - name: Install flake8
        run: poetry add --dev flake8

      - name: Run flake8
        run: poetry run flake8 .

  test:
    needs: lint
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          POSTGRES_USER: ${{ secrets.USER_DB }}
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD_DB }}
          POSTGRES_DB: ${{ secrets.NAME_DB }}
        ports:
          - 5432:5432

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies with Poetry
        run: poetry install --no-root

      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          NAME_DB: ${{ secrets.NAME_DB }}
          USER_DB: ${{ secrets.USER_DB }}
          PASSWORD_DB: ${{ secrets.PASSWORD_DB }}
          HOST_DB: localhost
          PORT_DB: 5432
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: poetry run python manage.py test

      - name: Run Bot tests
        run: poetry run python -m unittest discover tests/bot_tests/ -v

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/employee-task:${{ github.sha }} .

      - name: Push Docker image in Docker hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/employee-task:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/employee-task:${{ github.sha }} &&
          docker stop employee-task || true &&
          docker rm employee-task || true &&
          docker run -d --name employee-task -p 80:8000 \
          -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
          -e API_URL=http://localhost:8000 \
          ${{ secrets.DOCKER_HUB_USERNAME }}/employee-task:${{ github.sha }} \
          /bin/bash -c 'python manage.py runserver 0.0.0.0:8000 & python run_bot.py'
          "